config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
}
resources :games
put '/games/:id/favorite', to: "games#favorite", as: 'favorite_game'
get '/not_found', to:'pages#not_found', as: 'not_found'
get '*all', to: 'pages#not_found', constraints: lambda { |req|
  req.path.exclude? 'rails/active_storage'
}



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_login_form.html.erb
<div class="modal fade bd-example-modal-lg"tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Login to Continue</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="errors"></div>
        <%= simple_form_for(resource_name, :url => session_path(resource_name), remote: true) do |f| %>
          <%= f.input :email, label: "E-mail", wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}, required: false %>
          <%= f.input :password, label: "Password", wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}, required: false %>
          <%= f.input :remember_me, as: :boolean %>
          <%= link_to "Forgot your password?", new_password_path(:user) %>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Sign in', class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <a class="navbar-brand" href="#">LFG</a> %>
  <%= link_to 'LFG', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item nav-link mx3"><%= link_to "Host a game", new_game_path %></li>
    <li class="nav-item nav-link mx3"><%= link_to "Games", games_path %></li>
      <% if user_signed_in? %>
        <li class="nav-item nav-link mx3"><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
      <% else %>
         <li class="nav-item nav-link mx3"><%= link_to "Login", "", data: {toggle: "modal", target: ".bd-example-modal-lg"} %></li>
         <li class="nav-item nav-link mx3"><%= link_to "Sign Up", new_user_registration_path%></li>
      <% end %>
    
    </ul>
  </div>
</nav>

<%= render 'shared/login_form' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">LFG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    </ul>
    <span class="navbar-text">
      <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </span>
  </div>
</nav>