config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
}
resources :games
put '/games/:id/favorite', to: "games#favorite", as: 'favorite_game'
get '/not_found', to:'pages#not_found', as: 'not_found'
get '*all', to: 'pages#not_found', constraints: lambda { |req|
  req.path.exclude? 'rails/active_storage'
}



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :capacity, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  validates :title, presence: true
  validates :location, presence: true
  has_many :favorite_games, dependent: :destroy
  has_many :favorited_by, through: :favorite_games, source: :user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :destroy, :favorite]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:new, :edit]

  
  def index
    @games = Game.all
  end
  
  def create
    @game = current_user.games.create(game_params)
    if @game.errors.any?
      set_categories
      render 'new', :flash => { :alert => @game.errors.full_messages.to_sentence }
    else 
      redirect_to games_path
    end 
  end 

  def new
    @game = Game.new 

  end 

  def show 
    
  end 

  def favorite
    type = params[:type]
    case type 
    when "favorite"
      current_user.favorites << @game
      redirect_back(fallback_location: root_path, :flash => {:notice => "Favorited #{@game.title}"})
    

    when "unfavorite"
      current_user.favorites.delete(@game)
      redirect_back(fallback_location: root_path, :flash => {:notice => "Unfavorited #{@game.title}"})

    else
      # Type missing, nothing happens
      redirect_back(fallback_location: root_path, :flash => {:alert => "Something went Wrong"})
    end

  end 

  def update 
    @game.update(game_params)
    
    if @game.errors.any?
      set_categories 
      render 'edit'
    else 
      redirect_to games_path
    end
  end 

  def edit 

  end 

  def destroy 
    @game.delete
    redirect_to games_path, :flash => { notice: "Deleted"}
  end 

  private 

  def set_game
    begin 
    id = params[:id]
    @game = Game.find(id)
    rescue ActiveRecord::RecordNotFound
    redirect_to not_found_path, :flash => { :alert => "The game you're looking for doesn't exist" }
    end 
  
  end

  def game_params
    params.require(:game).permit(:title, :description, :location, :category_id, :capacity)
  end 
 
  def set_categories
    @categories = Category.all
  end 



  def authorize_user
    @game = current_user.games.find(params[:id]) 
    if @game.user_id != current_user.id
      redirect_back(fallback_location: root_path, :flash => {:alert => "I don't think so cheif"})
    end
  end 

  def check_user
    if !current_user
      redirect_back(fallback_location: root_path, :flash => {:alert => "You need to be logged in to do that"})
    end
  end 

end

app/helpers/games_helper.rb
module GamesHelper
    def favorite_link(game)
        if current_user
             if current_user.favorite_ids.include?(game.id)
                return link_to icon('fas', 'star'), favorite_game_path(game, type: "unfavorite"), method: :put
            else
                return link_to icon('far', 'star'), favorite_game_path(game, type: "favorite"), method: :put
            end
            return link_to icon('far', 'star'), new_user_registration_path
                

        end 

    end 
end

app/views/games/_form.html.erb
<%= simple_form_for @game, input_html: {class: "col-12"} do |f| %>
  <%= f.input :title ,wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}%>
  <%= f.input :location, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"} %>
  <%=f.association :category, as: :select, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}%>
  <%=f.input :capacity, wrapper_html: {class: "form-group"}, input_html: {class: "form-control", min: 1, max:10}%>
  <%=f.input :description, wrapper_html: {class: "form-group"}, input_html: {class: "form-control"}%>
  <%= f.button :submit,  class: "btn btn-primary" %>
<% end %>

app/views/games/edit.html.erb
<h1> Edit <%=@game.title%> </h1>
<%= render "form", game: @game%>

app/views/games/index.html.erb
<h1> Game Time </h1>

<div class='container'>
 <div class= 'row'>
    <%@games.each do |game|%>
      <div class="col-sm-4">
        <div class="card border-light">
        <%# SHOW PHOTO METHOD IN APPLICATION HELPER %>
          <div class="thumbnail"></div>
          <div class="card-body">
          <div class="d-flex justify-content-between">
            <h5><%= game.title %></h5>
                <%=favorite_link(game)%>
            </div>
            <h6 class="card-subtitle mb-2 text-muted">Created <%=time_ago_in_words(game.created_at)%> ago</h6>
            <p class="card-text"><%= game.description %></p>
            <div class= "d-flex justify-content-between">
              <%= link_to "show", game_path(game.id), class: "show-button" %>
              <h5><%= "$1" %></h5>
            </div>
          </div>
        </div>
      </div>
      <%end%>
 </div>
</div>

app/views/games/new.html.erb
  <h2> Host a Game </h2>
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">

    <%= render "form", game: @game%>
  </div>
</div>

app/views/games/show.html.erb
<h1><%=@game.title%> </h1>